### ISSUE TITLE
Tests for remaining vector instructions

### ISSUE THREAD

**Issue by lemmy-64** [lemmy-64/n64-systemtest#19]
VCL
VCH
VCR
VMRG

VAND
VNAND
VOR
VNOR
VXOR
VNXOR

VRCP
VRCPL
VRCPH
VMOV
VRSQ
VRSQL
VRSQH
VNOP

RSP_VEXTT until VNULL

**Comment by lemmy-64** [comment]
Bitwise done. Remaining:

VCL
VCH
VCR
VMRG

VRCP
VRCPL
VRCPH
VMOV
VRSQ
VRSQL
VRSQH
VNOP

RSP_VEXTT until VNULL

**Comment by lemmy-64** [comment]
Did VMRG and the the do-nothing and do-almost-nothing ones. Remaining:

VCL
VCH
VCR

VRCP
VRCPL
VRCPH
VMOV
VRSQ
VRSQL
VRSQH

**Comment by lemmy-64** [comment]
The previous list was missing the multiplications but also some have been added. Remaining now:

VRNDP
VRNDN
VMULQ
VMACQ

VRCP
VRCPL
VRCPH

VMOV

VRSQ
VRSQL
VRSQH

**Comment by lemmy-64** [comment]
All the "multiplications" are done. Remaining:

VRCP
VRCPL
VRCPH

VMOV

VRSQ
VRSQL
VRSQH

**Comment by lemmy-64** [comment]
VMOV done. Remaining:

VRCP
VRCPL
VRCPH

VRSQ
VRSQL
VRSQH

**Comment by danlehmann** [comment]
All done!

**Comment by lemmy-64** [comment]
All in
