### ISSUE TITLE
Help understanding SRAOpcodeTest

### ISSUE THREAD

**Issue by sarchar** [lemmy-64/n64-systemtest#60]
In my emulator I am failing on the SRAOpcodeTest and need help understanding why it's wrong (or perhaps the SRA test is wrong?)

```
Test 'SRAOpcodeTest' failed: a == b expected, but a=0xfffffffffc190a19 b=0xc190a19. Register $4

Running SRAOpcodeTest2...
Test 'SRAOpcodeTest2' failed: a == b expected, but a=0xffffffffffff8321 b=0xffffffff93218321. Register $4

Running SRAOpcodeTestShift0...
Running SRAOpcodeTestIntoItself...
Test 'SRAOpcodeTestIntoItself' failed: a == b expected, but a=0x10c850c b=0xffffffff850c850c. Register $3
```

As you can see, the tests are failing due to sign-extension.

The code for SRA is very simple. Failing code (Rust):

```rust
    fn special_sra(&mut self) {
        // truncate to u32, convert to signed, shift (fills 1s in the upper bits) and sign extend to u64
        self.gpr[self.inst.rd] = (((self.gpr[self.inst.rt] as u32) as i32) >> self.inst.sa) as u64;
    }
```

Working code:

```rust
    fn special_sra(&mut self) {
        self.gpr[self.inst.rd] = ((self.gpr[self.inst.rt] >> self.inst.sa) as i32) as u64;
    }
```

The first (non-working) implementation truncates rt to 32 bits, treats it as a signed int, shifts it right, and then sign-extends to 64 bits. The second working implementation shifts the full 64 bits and whatever bit ends up in bit 31 is sign extended to 64-bits.  This seems like it's in contradiction to the VR4300 datasheet:

![image](https://github.com/lemmy-64/n64-systemtest/assets/4928176/097a08b2-55f0-4a11-9023-ffd6ca8cc998)

From the psuedocode, at the 64-bit section:

1. Extend the shift amount by one 0 to make it a positive number (s)
2. Take bits GPR[rt] bits 31 downto s and place them in the lower bits (temp). Prefix those bits with GPR[rt] bit 31 repeated s times.
3. Set GPR[rd] to temp bits 31..0 and prefix that with temp bit 31 repeated 32 times to make a 64-bit int.

I don't see how any bits from the upper word end up in the lower word given the psuedocode in the datasheet.  If all 64 bits are shifted, then what makes the DSRA instruction different from SRA, other than the sign extension?

I hope someone is able to help me understand

Cheers

**Comment by Dillonb** [comment]
Yes, the datasheet is wrong. I've tested this behavior against real hardware using my tests here: https://github.com/Dillonb/n64-tests/releases/tag/latest - SRA shifts the entire 64 bit value, then truncates and sign extends.

**Comment by sarchar** [comment]
Thanks for the information.  Would it be correct to say that the implementation of SRA in the hardware is incorrect/a bug and that the datsheet was the *intended* behavior?

It seems to me that SRA *should* shift only the lower 32 bits (treated as a signed 32-bit number) while DSRA would do the doubleword.

**Comment by Dillonb** [comment]
Probably not, my theory is they just took a shortcut when implementing it in hardware. It behaves correctly when used with a 32 bit sign extended value.

**Comment by sarchar** [comment]
OK, thanks for the help understanding this
